### ISSUE TITLE
Settings not loading and JavaScript errors when `site_url` and `home_url` are on different domains

### ISSUE THREAD

**Issue by nestarz** [AxeWP/wp-graphql-headless-login#95] opened 2023-10-29 15:08 UTC
### Description

I am experiencing an issue with the Headless Login Settings addon. Despite trying different versions and disabling other addons, the Headless Login Settings are not loading properly. I have attached screenshots for reference.

Additionally, whenever I click on any button, I encounter JavaScript errors, as shown in the screenshots.
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/5360876/ac90c7d9-2857-4964-a618-fe98f892bba6)
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/5360876/147b7334-0cf4-440a-a8bf-eeb40a88390d)

### Steps to reproduce

1. Install Headless Login Settings addon.
2. Change the site url to the frontend url, make it different from the wordpress address url
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/5360876/397b4f97-c9e8-45a1-ab75-7f472d5053ab)
3. Attempt to access the settings page.
4. Click on any button. Nothing change, and the "Please wait while the settings are loaded" never change.

### Additional context

The Headless Login Settings should load without any issues, and clicking on buttons should not result in JavaScript errors.

### Plugin Version

0.1.4. Installed via the zip via the github release page (tried the last 5 releases its the same)

### WordPress Version

6.3.2

### WPGraphQL Version

1.17.0

### Additional enviornmental details

Site Language | en_US
User Language | en_US
Timezone | +00:00
Home URL | https://frontendurl
Site URL | https://wordpressinstallurl
Permalink structure | /%postname%/
Is this site using HTTPS? | Yes
Is this a multisite? | No
Can anyone register on this site? | Yes
Is this site discouraging search engines? | No
Default comment status | Open
Environment type | production
User count | 4
Communication with WordPress.org | WordPress.org is reachable

</div>

Headless Login for WPGraphQL | Version 0.1.4 by AxePress \| Auto-updates disabled
WPGraphQL | Version 1.17.0 by WPGraphQL \| Auto-updates disabled

Server architecture | Unable to determine server architecture

Web server | nginx/1.22.1
PHP version | 8.0.25 (Supports 64bit values)
PHP SAPI | fpm-fcgi
PHP max input variables | 5000
PHP time limit | 300
PHP memory limit | 1073741824
Max input time | 60
Upload max filesize | 512M
PHP post max size | 512M
cURL version | 7.83.1 OpenSSL/1.1.1s
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
Current time | 2023-10-29T15:33:39+00:00
Current UTC time | Sunday, 29-Oct-23 15:33:39 UTC
Current Server time | 2023-10-29T15:33:38+00:00

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL and Headless Login for WPGraphQL

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment] 2023-10-29 15:17
Hey @nestarz ,

Both in Slack and in this issue title you note that you have changed some settings from the default WordPress install, but im not seeing that noted in the `Steps to Reproduce` or anywhere else in that ticket.

Can you please update the issue description so the reproduction steps are comprehensive?

Additionally, in the environment details, please write what version of PHP you're using, whether you're using a release zip / branch source code / composer, and any other aspects about your environment (nginx vs apache, normal WP vs bedrock, etc).

The more detailed you are, the faster I can replicate and provide a solution/fix 🙏

**Comment by justlevine** [comment] 2023-10-31 10:52
Hey @nestarz 

It took a bit of sleuthing, but turns out that this is a bug/"design decision" in WordPress core; see WordPress/gutenberg/issues/1761

Personally, my recommendation to ensure cross-compatibility across the ecosystem is to host your WordPress install as a subdomain (`api.mysite.com` instead of `myapisite.com` ), but per the above GH issue, you can fix it with the following WP filter:

```php
/**
 * Use the WordPress url instead of the frontend url for REST API requests.
 *
 * @param string $url The original REST API URL.
 */
add_filter( 'rest_url', function( $url ): string {
  return str_replace( home_url(), site_url( '/' ), $url );
} );
```

(Updating the title to help future devs find this issue)

### Config
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/29322304/a4de1490-0d84-466f-86bd-eed90990ec1f)

### Before 
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/29322304/e1f3d71f-6353-465e-ad32-dc82765d8568)

### After
![image](https://github.com/AxeWP/wp-graphql-headless-login/assets/29322304/d3781650-767b-4a33-8072-31ed138f3182)

**Comment by justlevine** [comment] 2023-10-31 10:55
(Closing as there's nothing actionable in this plugin)

**Closed** 2023-10-31 13:21 UTC
Labels: workaround provided 🩹, status: wontfix 😶, type: bug 🐛, component: settings
